### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by reapazor** [dotBunny/VSCode#1]
After testing VSCode 0.7.x on Windows, I've found that my VSCode doesn't like the idea of debugging "mono". 

Reached out to the VS Code team for some direction.

**Comment by reapazor** [comment]
Made contact!  Looks like were going to have to wait a bit on this one ... but it may come for all you windows folks.

**Comment by DDReaper** [comment]
If it helps, I can sort the windows side @reapazor 
Been talking to the VSCode team and they pointed me your way.
Should just need some #If's to block out non-windows functions.  otherwise, testing so far seems to work. 
Will push a pr with updates shortly

**Comment by reapazor** [comment]
The windows side of the plugin should work mostly, its the debugging part within Unity that isn't supported directly with Visual Studio Code

**Comment by DDReaper** [comment]
Yup, so for Windows, that just needs hiding behind a #if for mac :dancer:

**Comment by reapazor** [comment]
(it already does - for the most part)

**Comment by DDReaper** [comment]
Ideally, the following
```

		[MenuItem ("VS Code/Enable Logging")]
		static void MenuEnableDebug ()
		{
			Menu.SetChecked ("VS Code/Enable Logging", !Debug);
			Debug = !Debug;
		}
```
shouldn't display for windows if it doesn't work :dancer: 

I see where you have a separate section for determining the windows port (which is odd because it finds a port on mine).  As the VSCode team have stated, it won't work (as yet), so shouldn't be an option

**Comment by reapazor** [comment]
Logging is actually just outputting debug messages to the Unity console  ... Enabled is the global catch all.

Sadly you cant have Visual Studio Code for editing, but still be able to open in MD/VS to debug as the project file has to be scrubbed. Hence if you disable the integration it reverts all settings to work with the other editors for you.

**Comment by reapazor** [comment]
I realize the naming is off, I'll try to make a note tonight to refactor the name :)

**Comment by DDReaper** [comment]
Reading through the code, that statement is so obvious now.
I think the VSCode guys led me down the wrong path indicating that you had the mac debugging option already implemented, whereas you're only grabbing the debug port and writing it to the setting file.

however I probably wouldn't keep getting and writing the port on play all the time.  Might be better to only do it in Sync project.  VSCode doesn't react well to change while it's running at present so I've found

**Comment by reapazor** [comment]
Umm ... mac debugging does work? All it needs to do is write that port for Visual Studio Code to use :) ... you just have to start the debugging in Visual Studio Code once its running.

<img width="1342" alt="screenshot 2015-09-03 18 08 59" src="https://cloud.githubusercontent.com/assets/99292/9673124/01060f28-526f-11e5-8554-033ef05a9eda.png">

I think it might be advantageous for me to create a HOWTO video.

**Comment by DDReaper** [comment]
From my experience with the UI Extensions project, The community loves videos.  Nothing fancy, just a 2 min video showing it's use.
Need to sync that with the VSCode teams documentation as well.

I know the debugging works in VsCode, however I was led to believe you'd done something "extra" :D,
Will be even better when they improve / expand the support.

**Comment by reapazor** [comment]
Ahh ... naw I just made it automatic on that front, basically ... you would need to set the port every time in Visual Studio Code you wanted to debug something.

The plugin does a few things:
- Makes projects/solutions so that they can open in Visual Studio Code and not have OmniSharp barf at them
- Opening to line/etc
- Automatic port writing for debug

**Comment by DDReaper** [comment]
Question is however:
* how often is the port likely to change
* will VSCode actually react to a port change while it's running (so far I've found it only reads config on start-up, so you would need to close it for new settings).  Although this could change in the future

Additionally, if you keep your config file in your source control, you could be causing a commitable change on every run which might confuse people.  IMHO

**Comment by reapazor** [comment]
Not sure on Unity's side, however on play mode enter i poll for the port and save it (incase it changes --- i really should inquire with Unity about that, specifically when and if it can change).

Visual Studio Code will react to port changes for debug, as you must start debugging inside of it at which point it does use the config.

The whole .vscode folder would in theory be in constant flux, but that could be why they've got it started with a "." ... most "hidden" folders are meant to be excluded from versioning. That config folder is meant to be workspace related files.

**Comment by reapazor** [comment]
https://vimeo.com/dotbunny/vscode, I'll update it once things are firmed up and fixed on the Visual Studio Code front.

**Comment by DDReaper** [comment]
Tested, all working good on Windows except for OmniSharp, but that'll be because I'm still on 0.7.  Will re-test on 0.8

Will have to warn users not to use it without 0.8 :D

**Comment by reapazor** [comment]
Everything should work except debugging :( With Unity moving to SOAP/RPC approach for debugging in the future this functionality should come to both mac/windows deployments and I will have to update then.  I've already tipped off the Visual Studio Code team about it and they've reached out to the corresponding Unity team ... so there should be some Visual Studio Code babies at some point.

**Comment by DDReaper** [comment]
it's because I'm on 0.7, the settings files don't work :D, so will re-test once I've gotten hold of 0.8
