### ISSUE TITLE
Path with spaces not working under Windows 10

### ISSUE THREAD

**Issue by Maweypeyyu** [dotBunny/VSCode#102]
Hi,

I'm not totally sure what the exact issue is, but having a project which contains spaces (the project is on a different drive, too) can't be opened by VSCode. The loaded project looks like "D:\this\ is\ only\ one\ folder\".
Removing the call `EscapePathSpaces` before assigning `args` to `proc.StartInfo.Arguments` solved the issue for me though.

As I don't know what the exact cause is (Win10? Or because of the newest VSCode version?) I thought I'll just let you know.

Best,
 Mawey

**Comment by mseqs** [comment]
Fixed, the problem was on the plugin, the EscapePathSpaces call is not needed on a Windows system
