### ISSUE TITLE
VSCode doesn't found Visual Studio Code.app

### ISSUE THREAD

**Issue by sanchezpaco** [dotBunny/VSCode#103]
Hi,

I recently installed the VSCode plugin on my current project on Unity and I can see the VSCode tab on preferences.

The problem I have is when I try to open a script, I get the next error:

Code executable in '/Applications/Visual Studio Code.app' not found. CheckVisual Studio Code installation and insert the correct path in the Properties menu
UnityEngine.Debug:LogError(Object)
dotBunny.Unity.VSCode:PrintNotFound(String) (at Assets/Plugins/Editor/VSCode.cs:384)
dotBunny.Unity.VSCode:autodetectCodePath() (at Assets/Plugins/Editor/VSCode.cs:419)
dotBunny.Unity.VSCode:get_CodePath() (at Assets/Plugins/Editor/VSCode.cs:53)
dotBunny.Unity.VSCode:UpdateUnityPreferences(Boolean) (at Assets/Plugins/Editor/VSCode.cs:1119)
dotBunny.Unity.VSCode:VSCodePreferencesItem() (at Assets/Plugins/Editor/VSCode.cs:819)
UnityEditor.HandleUtility:EndHandles()

My Visual Studio Code.app it's correctly placed on /Applications and I can open it outside Unity.
From the menu External Tools in unity, I was capable to choose Visual Studio Code as default Unity editor too.

Where is the error? Thanks!
<img width="766" alt="screen shot 2016-05-30 at 22 22 19" src="https://cloud.githubusercontent.com/assets/4403252/15657962/95c5407c-26b6-11e6-9956-01cb7c33ff9b.png">

**Comment by reapazor** [comment]
Grab latest :) I’ve fixed this now! Thanks for the heads up.


---
Matthew Davey

**Comment by sanchezpaco** [comment]
It works! Thank you very much!
