### ISSUE TITLE
Unity freezes on OSX 

### ISSUE THREAD

**Issue by machernator** [dotBunny/VSCode#112]
Every time I add the Package to a project, Unity freezes. No error message, just an endless rotating "Wait" Icon.

Unity 5.3.5f1 personal
MacBook Pro (Retina, 15", End of 2013)
2,3 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB

**Comment by reapazor** [comment]
That does seem strange ... UAS package i take it ... I'll have a check of this, but it sounds like the download might be corrupt?
