### ISSUE TITLE
Definition Errors at Runtime

### ISSUE THREAD

**Issue by BHoney** [dotBunny/VSCode#117]
For some reason, Unity will suddenly "lose" the plugin while running, throwing the following errors and removing all the menu options.

```Assets/VSCode/Plugins/Editor/VSCode.cs(23,25): error CS0101: The namespace `dotBunny.Unity' already contains a definition for `VSCode'```

```Assets/VSCode/Plugins/Editor/VSCode.cs(1214,18): error CS0101: The namespace `dotBunny.Unity' already contains a definition for `VSCodeAssetPostprocessor'```

It usually occurs something up to three minutes of opening a project.  At first I thought it was after the first run of the game scene but after waiting for a bit it turns out it just happens at the same time no matter what.

**Comment by reapazor** [comment]
Hmm, I tried to reproduce this issue but wasn't able too locally. 
It sounds like something todo with your install unfortunately. :(
