### ISSUE TITLE
Not opening editor with Insiders

### ISSUE THREAD

**Issue by nfantone** [dotBunny/VSCode#119]
As described in https://github.com/dotBunny/VSCode/issues/118#issuecomment-238012101, selecting "_Assets > Open C# Project in Code_" or clicking the "_Open_" button on the inspector for script files, doesn't seem to have any effect.

Using:
- vscode: `1.5.0-insider` 
- dotBunny/VSCode plugin: `2.7`
- Unity3D: `5.4f3`

More on PR https://github.com/dotBunny/VSCode/issues/118.

**Comment by jvlppm** [comment]
My pull request did change the launch command on OSX, so it would launch the vscode indicated by the selected vscode path

https://github.com/dotBunny/VSCode/pull/114/files

This pull request was merged, but a later commit 
https://github.com/dotBunny/VSCode/commit/1e1a2e01c83a01c356dd6317b1fba2ae9771f30f

did change this back to the old behavior, feeling like the file content was replaced by an older version during conflict resolution.

**Comment by reapazor** [comment]
I think the intent with the below block was to stick to using the typical launch properties, I'll grab the latest insiders and see about that tonight ... I 'thought' this would have handled it. Maybe its the wrong domain.

```csharp
#if UNITY_EDITOR_OSX
            proc.StartInfo.FileName = "open";

            // Check the path to see if there is "Insiders"
            if (CodePath.Contains("Insiders"))
            {  
                proc.StartInfo.Arguments = " -n -b \"com.microsoft.VSCodeInsiders\" --args " + args.Replace(@"\", @"\\");
            } 
            else 
            {
                proc.StartInfo.Arguments = " -n -b \"com.microsoft.VSCode\" --args " + args.Replace(@"\", @"\\");
            }

            proc.StartInfo.UseShellExecute = false;
#elif UNITY_EDITOR_WIN
            proc.StartInfo.FileName = CodePath;
	        proc.StartInfo.Arguments = args;
            proc.StartInfo.UseShellExecute = false;
#else
            proc.StartInfo.FileName = CodePath;
	        proc.StartInfo.Arguments = args.Replace(@"\", @"\\");
            proc.StartInfo.UseShellExecute = false;
#endif
```

**Comment by frankprogrammer** [comment]
Everything is working fine with:

   - vscode: 1.5.0-insider
   - dotBunny/VSCode plugin: 2.7
   - Unity3D: 5.3.3p1

**Comment by nfantone** [comment]
@frankprogrammer How did you install the plugin? Did you use the Asset Store? Are you on OSX?

**Comment by nfantone** [comment]
@reapazor I don't believe the domain is the problem here. As I mentioned in #118 , if you edit `proc.StartInfo.UseShellExecute = false;` and set it to `true`, the editor opens just fine (along with a warning in Unity's console).

**Comment by reapazor** [comment]
Ahh i was just looking at the top of that issue, i see what you mean. 
Is that specific to insiders only?

**Comment by frankprogrammer** [comment]
Ah didn't see this issue was talking about the Asset Store version
originally. I got it through GitHub on June 23rd and it has updated on its
own a couple of times. Update Timer set to 1 Day. Running OS X 10.11.3 and
10.11.6. Also tried it with Unity 5.4.0f3 and it works too. Everything
checked in settings except Always Write Launch File and my VS Code Path
is /Applications/Visual Studio Code - Insiders.app

All my proc.StartInfo.UseShellExecute are set to false.

**Comment by nfantone** [comment]
So maybe I am doing something wrong. Just now, I created a new project,
installed the plugin from scratch, activate it and still nothing.

Could somebody else try it out and report?

**Comment by reapazor** [comment]
I'm closing this, but reopen if it still presists in the latest of all things :)
