### ISSUE TITLE
New Class Not Being Detected By VSCode?

### ISSUE THREAD

**Issue by vexir** [dotBunny/VSCode#12]
Just created a new C# class in Unity through the editor. VSCode hasn't picked it up yet. I've tried restarting both applications, enabling and disabling integration, force syncing the project, opening the project through the VSCode menu... no luck.

The class is quite simple - just a MonoBehavior that uses the UnityEngine and has a bunch of tweakables in it.

```
using UnityEngine;

public class HUDConfig : MonoBehaviour {

	[Header("HUD Configuration")]
	public Vector3 pulseTargetScale = Vector3.one;
	public float pulseScaleTime = 1.0f;
	public iTween.EaseType pulseScaleEaseType = iTween.EaseType.easeInSine;
	public float pulseInterDelayMax = 1.25f;
	public float pulseInterDelayMin = 0.4f;
	public Vector3 pulseShakeMax = Vector3.one;
	public Vector3 pulseShakeMin = Vector3.zero;
	public GameObject streakContainerPrefab = null;
	public int fastestPulseAtStreak = 75;
}
```

**Comment by reapazor** [comment]
Did you either:

Double click on the code file to open it ? 

or

Use the open project method?



Unity doesnt automatically write out the project files :)

**Comment by vexir** [comment]
VSCode actually underlines the class name with a red line, which I suppose indicates that it doesn't know that class exists. It knows the file exists, because I'm able to Cmd+P to HUDConfig.cs. When utilizing an instance of the HUDConfig class, Intellisense doesn't even pop up.

My Assembly-CSharp.csproj has the following line:

```<Compile Include="Assets\Scripts\Config\HUDConfig.cs" />```

**Comment by vexir** [comment]
@reapazor Still having this issue - any ideas?

**Comment by reapazor** [comment]
Something I've noticed a few times is that there is a delay before classes / etc get added to intellisense.

For example, I had a test library in my test project, where I could see the intellisense for the library name, it took a minute or so after referencing it before the classes of that library came up.

It sounds like a VS Code issue more then an issue of the unity interface.
