### ISSUE TITLE
Error getting response stream

### ISSUE THREAD

**Issue by phest** [dotBunny/VSCode#127]
Getting this error when launching Unity:

```
[VSCode] Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
UnityEngine.Debug:Log(Object)
dotBunny.Unity.VSCode:CheckForUpdate() (at Assets/Plugins/Editor/VSCode.cs:493)
dotBunny.Unity.VSCode:.cctor() (at Assets/Plugins/Editor/VSCode.cs:310)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])
```

Windows 10. Tested on these versions, got the same error:
- Version 5.4.0f3
- Version 5.3.6f1
- Version 5.3.4f1

**Comment by reapazor** [comment]
I've seen this before on Mac installs, particularly related to a bad HTTPS protocol implementation in Mono. Do you have anything 'custom' installed? Mono on Windows by chance? What versions of .Net are installed?

**Comment by phest** [comment]
I don't think I have Mono (mono command isn't available), or a custom install of .net, but I'm not sure how to check that.

In Unity, `Debug.Log(System.Environment.Version);` outputs `2.0.50727.1433`

Anything else I can do?

**Comment by reapazor** [comment]
I'm gonna assume you've upgraded to a newer version of Unity? and hopefully this is fixed now.
