### ISSUE TITLE
VSCode not recognising unity debugger

### ISSUE THREAD

**Issue by MetaDev** [dotBunny/VSCode#130]
When I enable "Use Unity Debugger" in the preferences a warning is given that the Unity Debugger is not installed. But the debugger is installed and even installing it through the warning does not fix it.

**Comment by reapazor** [comment]
Please verify that the Debugger is installed in the extensions of Visual Studio Code, should look a little like this.

<img width="624" alt="screenshot 2017-02-06 09 59 44" src="https://cloud.githubusercontent.com/assets/99292/22652205/9613b30c-ec53-11e6-8a46-a4a227e71a8d.png">
