### ISSUE TITLE
Double clicking unity exception no longer opens script at error line

### ISSUE THREAD

**Issue by raldred** [dotBunny/VSCode#131]
I've noticed recently double clicking an exception no longer opens the offending script at all.
It works fine if I switch back to mono develop. The script is opened at the offending line.

With VS code integration enabled nothing happens.
Assets -> Open C# project in VSCode opens correctly.
Double clicking script in Project window opens the script fine.

Windows 10
Unity 5.3.6
VS Code 1.5.3
VS Code unity plugin 2.70-release

**Comment by sorab2142** [comment]
Can confirm, I have the same issue.
Windows 10
Unity 5.3.6p6 and 5.4.1f1
VS Code 1.5.3
VS Code unity plugin 2.70-release

**Comment by CanisLupus** [comment]
I'm also having the same issue. It might have started happening after updating VSCode to version 1.5 (not completely sure).

**Comment by reapazor** [comment]
So what is the recommendation ? Leave VSCode plugin as is ... and hope that the MS team fixes on their end?

**Comment by CanisLupus** [comment]
Hmm... Maybe use omid3098's version of the file until the next stable VSCode version...? I think I'll be doing that. The fix seems to work nicely, which mine didn't. :)

**Comment by reapazor** [comment]
Makes sense, people use it till the next stable ... i would merge all the spacing changed ;|

**Comment by omid3098** [comment]
You're welcome and sorry about spacing changes! auto format done with vscode!
nothing has changed in code except breaking file absolute path.
Project path goes to process and remaining relative path goes to vscode file path.

**Comment by raldred** [comment]
Seems like it's fixed in the latest Insider build
