### ISSUE TITLE
Editing Evolved doesn't work (Go to Definition, Find References)

### ISSUE THREAD

**Issue by rafalswiech3** [dotBunny/VSCode#134]
VS Code version: 1.6.1
C# Extension version: 1.4.1

I've got problem MacOS Sierra

I installed latest VSCode and C# omnisharp extension but I can't use:

Go to Definition
Find All references
and other tools from editing evolved of VSCode.
When I try to use them nothing happens.

I'm working with Unity3D project.

Also I can't see that options in context menu as on screenshot:

![zrzut ekranu 2016-10-31 o 18 13 33](https://cloud.githubusercontent.com/assets/23174038/19883515/102db628-a015-11e6-823b-2ff210e544b9.png)

**Comment by sorab2142** [comment]
1. Check the extension for C#, you don't need the "recommended" C# extension, what you need is the Legacy Omnisharp extension.
2. In the bottom status bar, next to the part where it shows the language of the current file (C#) there is a fire icon, if you have more than one solution (.sln) file, it will be green and say Select Project. 
3. If not it will show Running (for when it is loading) and then once loaded, it will display the name of your .sln file

Hope this helps.

**Comment by rafalswiech3** [comment]
Thank you so much! It worked. 

Also I had to update mono to latest version.
