### ISSUE TITLE
vscode no longer autocompletes c# nor Unity API's

### ISSUE THREAD

**Issue by guivho** [dotBunny/VSCode#135]
Last week, this stopped working, probably related to one of the extension updates. I am running (on Windows 10) Visual Studio Code v1.6.1 and have following extension versions (I just list the ones that I think to be relevant):

- C# for Visual Studio Code (powered by OmniSharp) v1.4.1
- Legacy OmniSharp Support for Visual Studio Code v0.3.3

I think I need both, but problem persists when using only one of them (either one)

I tried it with and without 'C# Extensions' by jchannon v1.0.8: makes no difference.

I am not sure what exactly goes wrong. One of the symptoms ia that VSCode no longer shows the number of references to a variable just above its declaration.

Also, it no longer detects spelling errors in api calls nor class references, e.g. it readily accepts RigidBody2D iso Rigidbody2D as a class name, which is than rejected when returning to Unity.

Needless to say that it does not autocomplete, unless I'm referencing or typing something that already occurred in the file being edited.

This problem changed the lightning fast super pleasant editor into some dull often enervating tool.

Please advise.

**Comment by reapazor** [comment]
Remove the legacy Omnisharp extension.

**Comment by guivho** [comment]
As I said in the previous message, that does not make any difference, the problem persists :(
