### ISSUE TITLE
installing unity debugger vsix file failed

### ISSUE THREAD

**Issue by 3ace** [dotBunny/VSCode#141]
when installing Unity Debugger from preferences menu, instead of installing the vsix file, VS Code would open it.

I'm using VS Code 1.7.2

probably this link below has something to do with this bug

https://code.visualstudio.com/Docs/extensions/install-extension

**Comment by reapazor** [comment]
We're currently using a link to the package (https://unity.gallery.vsassets.io/_apis/public/gallery/publisher/unity/extension/unity-debug/latest/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) That should automagically open with Visual Studio Code and install. 

Hopefully this is resolved now? (please reopen if it still isnt working)
