### ISSUE TITLE
Debugger doesn't stop at breakpoint

### ISSUE THREAD

**Issue by kikutano** [dotBunny/VSCode#142]
I'm on a Mac, with **Unity 5.5.0f3**, **VSCode 2.7**, **Visual Studio Code 1.8.1** when i start the game on Unity i can see the CallStack and Threads in Visual Studio Code, but the breakpoint turns in grey and if i try to Enable/Disable this error is launched:

**_"error while processing request 'setBreakpoints' (exception: Cannot perform member binding on `null' value)_**"

The breakpoints are ignored. I don't know what i can do to fix this problem, the console say to me **_"UnityDebug: Attached to Unity editor process 'Unity' (1806)"_**. Any help?

Thanks!

**Comment by nmquan-dev** [comment]
This may be a bit late, but Do u have any other plugins installed? if u do, i suggest disable them all for test. And if your code is pure .Net 3.5 syntax then, is should work. In my case, i have C#6 parser plugin install which doesnt play very well with .vscode debugger.

**Comment by kikutano** [comment]
I'm trying with an empty Unity Project. On Visual Studio Code i've disabled all plugins but i've always the same error. I don't really know what can i do.

**Comment by reapazor** [comment]
I just validated that it still works with 5.5.0f3 (with the described versions) as well as in the newer 5.5.1. It sounds like the mono stack might be an issue.

<img width="624" alt="screenshot 2017-02-06 09 59 44" src="https://cloud.githubusercontent.com/assets/99292/22652072/0239ac72-ec53-11e6-8c5d-fbbe81b53c84.png">

Now mine has some extras, but thats how I have it :)
