### ISSUE TITLE
Opening Scripts from Unity redirects to CLI.js file in VSCode Editor

### ISSUE THREAD

**Issue by Suj33t** [dotBunny/VSCode#154]
When i try to edit scripts by opening them through Unity Editor , the File opens in VSCode but CLI.js file is opened parallel to it and it becomes focused tab.

**Comment by oouo-diogo-perdigao** [comment]
+1

**Comment by tomwilliamfranklin** [comment]
This is a very old post, but when looking online I couldn't find a solution to this problem. But from my understanding its to do with the pop up which happens before vscode opens, "Do you want to allow this app to make changes to your device?". I found that the only way to stop this popup, and as a result stop the cli.js file opening, was to disable these pop ups altogether.  

Going to Change User Account Control Settings and setting it to "Never notify me when" did the trick for me, but of course, this does create a security risk.
