### ISSUE TITLE
crash with unity2017.2 ??

### ISSUE THREAD

**Issue by chiuan** [dotBunny/VSCode#156]
crash with unity2017.2 ??

always ....please help...

**Comment by thorning** [comment]
I get a lot of crashes with 2017.2 as well. It seems to happen 50% of the time when I press play after making code changes.

A loader window popup with title "VSCode" and text "Checking for updates". I get this every time I edit code and return to unity, and then again when I press play in the editor, but it only crashes when I press play.

I have my platform set to iOS and use .net 4.6

**Comment by thorning** [comment]
It seems the error happen in the function `CheckForUpdate` in `VSCode.cs:480`. Disabling this with a return statement line 1 solved the crashes as a quick fix.

**Comment by jasontuttle** [comment]
I'm seeing crashes as well on Unity 2017.2 -- It happens every time I quit Unity. Just tried removing VSCode, and the crashes went away. I also tried disabling "CheckForUpdate" per thorning's comment above. No luck, still crashes every time I quit Unity.

**Comment by chiuan** [comment]
@jasontuttle i have fix this .

just comment the Function "UpdateUnityPreference" >   "// FixUnityPreferences();" the last line.
it works.

**Comment by jasontuttle** [comment]
@chiuan is correct: Commenting out the last line of the Function "UpdateUnityPreference" > "// FixUnityPreferences();" fixes the problem.

**Comment by reapazor** [comment]
That line was used to fix an issue where preferences werent being read. Might mean the bug in Unity was resolved with that and would stop the crash accordingly.?
