### ISSUE TITLE
symbolic links not followed correctly when opening in VSCode from Unity

### ISSUE THREAD

**Issue by abryden** [dotBunny/VSCode#17]
If you open a file in a folder that is symbolically linked it will open in the file's original location as opposed to the linked directory.

**Comment by abryden** [comment]
I did some investigation and this appears to be a visual studio code issue. I think the workaround may be to use hardlinks but then that messes with git so I may be stuck browsing in the solution for now.

**Comment by abryden** [comment]
https://code.visualstudio.com/issues/detail/19526

**Comment by reapazor** [comment]
I just wanted to say, thank you for identifying what is a Visual Studio Code issue, versus the plugin.
Not many people do :)
