### ISSUE TITLE
Debugger won't attach

### ISSUE THREAD

**Issue by zsculpt** [dotBunny/VSCode#20]
Tried various settings in the launch.json files. Can't get it do attach or hit any breakpoints.

**Comment by reapazor** [comment]
What platform are you on?
What version of Unity?

**Comment by zsculpt** [comment]
OS X 10.10.5 and Unity 5.2.1f1

**Comment by martinpi** [comment]
Same here. Same versions.

**Comment by reapazor** [comment]
There were apparently a bunch of fixes in 0.9.0 to help with attaching / etc.

Can you possibly turn on the output messages option and see if it is finding the port? and if that port is being written to your launch settings file for vscode.

**Comment by zsculpt** [comment]
Yeah, I verified that the launch.json file is being written with the correct port:

"version":"0.1.0",
	"configurations":[ 
		{
			"name":"Unity",
			"type":"mono",
			"address":"localhost",
			"port":56139
		}
	]

**Comment by zsculpt** [comment]
Damn! Just upgraded to the new (today) VS Code 0.9.1 and the debugger worked perfectly the first time! ...and have NOT been able to get it to attach since. :-( Tried restarting apps, comp, etc. No go. There must be some cache file it's referencing??

**Comment by zsculpt** [comment]
OK, I was finally able to solve this! Not sure the exact file that was the culprit but basically dumped all of the generated code files from the Unity project folder (.csproj, obj/Debug). You can even delete the Project Settings and Library folder if you want. Unity will re-create everything and the VSCode attaches and works perfectly fine.

**Comment by reapazor** [comment]
Sounds like the files were being locked and not able to be overwritten? 
Version control? Perforce?

**Comment by Shrike78** [comment]
Hi I'm unable to connect debugger too. If I try to start debug I get a "Debug adapter process has terminated unexpectedly" error on vscode.

I'm using latest vscode 0.10.3, latest unity 5.2.3f1 and Yosemite os

**Comment by Shrike78** [comment]
Can the problem be related to the mono version installed in the system? I'm not speaking about unity monodevelop version. 

Having no luck with your plugin I've found this: http://forum.unity3d.com/threads/vs-code-unity-debugger-extension-preview.369775/

Following the instructions I've installed latest monodevelop version (and the vscode plugin provided). After that I was able to successfully connect the debugger also using your plugin

**Comment by reapazor** [comment]
Indeed, Unity's plugin provides the right debugger framework (instead of relying on Mono internal). I've been chatting with them about the future of my plugin. 

Ultimately they won't be able to get their support 'fully' for another 6 months and it sounds like they'd like mine to stick around for that time. One thing that I'd like to add to mine is installing that debugger extension for you automatically, etc.

We'll see ... I haven't had time to evaluate doing that yet, work keeps my occupied.

**Comment by reapazor** [comment]
I'm going to close this now with the addition of the Unity Debugger side of things to the plugin. My suggestion is to use it :)

**Comment by zsculpt** [comment]
This is still a continuing problem, and I'm now no longer able to fix it by deleting the aforementioned files. I have the VSCode debugger installed, as well as the VSCode editor extension and all the boxes checked. The debugger spits out a message in the console that it attached, and then about 3 seconds later it disconnects. Can't hit any breakpoints. :-(

**Comment by loris-github** [comment]
@zsculpt 
buddy, do you solve that attached at first and then disconnect ?  same problem i meet :-(

**Comment by zsculpt** [comment]
No - I gave up trying to use the debugger until someone can provide any more troubleshooting steps. It just doesn't work.
