### ISSUE TITLE
OmniSharp just says "Select Project"

### ISSUE THREAD

**Issue by vexir** [dotBunny/VSCode#21]
Just upgraded to 0.9.0 and now when I have Enable Integration selected there is no intellisense and OmniSharp says "select project". What's up?

**Comment by reapazor** [comment]
Not sure to be honest, I'll be doing some bug fixes tomorrow.. so i'll get 0.9.0 working then (or before depending on when i have a spare moment)

**Comment by reapazor** [comment]
<img width="1361" alt="screenshot 2015-10-07 17 21 48" src="https://cloud.githubusercontent.com/assets/99292/10351511/ed7cb498-6d17-11e5-8b92-0ecc511c3279.png">

Looks fine in 0.9.0, via a test project ... do you have any more details that might help?

**Comment by vexir** [comment]
The editor preferences still show MonoDevelop as the code editor. Perhaps
that helps?

**Comment by vexir** [comment]
Is there any information I can give you? The OmniSharp log perhaps?

**Comment by jghazarian** [comment]
I got this happening as well. Microsoft included a comment about it in the "Common Questions" section for integration with this plugin: https://code.visualstudio.com/Docs/runtimes/unity

You should be able to just select the project by clicking on the option it gives you. Hope that helps.

**Comment by vexir** [comment]
There is no option. Clicking on the OmniSharp label does nothing :(

**Comment by reapazor** [comment]
There really should only be one solution in the folder, Visual Studio Code should open it by default. 

I'm not sure why @vexir you are having such bad luck with the plugin :(

**Comment by kreso22** [comment]
Hey @vexir , I think we have the same problem. What helped me was to quit Unity. Delete all *.sln files in my project (one level up, from Assets). Restart Unity and then "Start C# in Code".

Before doing this I had 10 sln files, now 5.
My guess is that because I used Xamarin it created it's own sln files. Or something like that happened.

Anyhow, good luck!

**Comment by reapazor** [comment]
This makes me think maybe I should add something in to wipe out all other data.... a datapocolypse if you will.
