### ISSUE TITLE
The specified runtime path 'default' does not exist.

### ISSUE THREAD

**Issue by hartbit** [dotBunny/VSCode#23]
OmniSharp has a few errors when opening my project, including:

```
[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations /Users/david/.dnx/runtimes/dnx-mono.default
/Users/david/.dnx/runtimes/kre-mono.default
/Users/david/.dnx/packages/KRE-Mono.default
/Users/david/.k/runtimes/dnx-mono.default
/Users/david/.k/runtimes/kre-mono.default
/Users/david/.k/packages/KRE-Mono.default
/Users/david/.kre/runtimes/dnx-mono.default
/Users/david/.kre/runtimes/kre-mono.default
/Users/david/.kre/packages/KRE-Mono.default.
```

**Comment by Souk21** [comment]
Check that https://github.com/aspnet/home
it solve the issue for me

**Comment by hartbit** [comment]
Indeed it works. I'm confused why it's necessary.

**Comment by reapazor** [comment]
Just a heads up that this particular error doesn't effect the project, it drives me NUTS that it is in the log ... but nothing I can do, its not part of the unity toolchain.

**Comment by flq** [comment]
Um...what worked?

**Comment by xCyborg** [comment]
same issue here

**Comment by ghachey** [comment]
I think they are still working at this see https://github.com/OmniSharp/omnisharp-roslyn/issues/347 and https://github.com/Microsoft/vscode/issues/126
The current work around is to either change the user location for the runtimes to a symlink to the global location of runtimes or uninstall from global and reinstall the runtimes into the user location both of which are not ideal solutions. More details on the work-arounds can be found at http://stackoverflow.com/questions/33976187/omnisharp-dnx-dnxpaths-the-specified-runtime-path-default-does-not-exist

**Comment by xlfishbone** [comment]
Be sure to run 
"dnvm upgrade"

I ran into this issue b/c I didn't read all the instructions.

**Comment by jwoodall** [comment]
Following the install for osx at:  https://github.com/aspnet/home instructions removed the error for me

**Comment by DDReaper** [comment]
Ha Ha, thanks for the clarification @xlfishbone I too also missed that subtlety :dancer: 
ALso got another prompt when I next started up to Restore the references from my project.json

**Comment by PierBover** [comment]
> "dnvm upgrade"

Thanks @xlfishbone that did it for me too.
