### ISSUE TITLE
Unsafe code requires the `unsafe' command line option to be specified

### ISSUE THREAD

**Issue by hartbit** [dotBunny/VSCode#24]
OmniSharp has errors open my project. I think it has something to do with a plugin using unsafe DLL code:

```
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] Unsafe code requires the `unsafe' command line option to be specified
```

Any ideas on how to fix this in VSCode?

**Comment by reapazor** [comment]
Currently, Visual Studio Code doesn't have any way that I know of to pass parameters to the compiler (roslyn). I would pass your request on up the Visual Studio Code teams' chain about adding that feature, then I would integrate based on it.

https://visualstudio.uservoice.com/forums/293070-visual-studio-code

**Comment by hartbit** [comment]
Well, normally, the project option `<AllowUnsafeBlocks>True</AllowUnsafeBlocks>` is supposed to fix this issue. For some some reason, even after manually modifying csprojs, OmniSharp is still reporting those errors.
