### ISSUE TITLE
Cannot start Omnisharp. Wrong Mono Version.

### ISSUE THREAD

**Issue by mmoczkowski** [dotBunny/VSCode#28]
[ERROR] Error: Cannot start Omnisharp because Mono version >=4.0.1 is required. See http://go.microsoft.com/fwlink/?linkID=534832#_20001

The latest mono version is installed /Library/Frameworks/.

**Comment by reapazor** [comment]
Your $PATH probably hasn't been updated to reflect the 'current' version. 


For example ....

```bash
MattBook:~ reapazor$ cat .bash_profile 
export P4CONFIG=p4config.txt
export PATH=/Library/Frameworks/Mono.framework/Versions/Current/bin/:${PATH}
```

**Comment by mmoczkowski** [comment]
That's it, thank you!
