### ISSUE TITLE
Should Opening An Asset force Open The Project

### ISSUE THREAD

**Issue by reapazor** [dotBunny/VSCode#3]
Right now opening an asset directly from Unity does not force open the project first, I think I might want to change this behaviour.

**Comment by DDReaper** [comment]
Not sure you can interrupt the editor behavior when opening scripts. Simply having the option in the menu to open VSCode first should be enough.

**Comment by reapazor** [comment]
Heh :) Oh I already do interrupt Unity ... this is purely a discussion point :)

I think it might be worth while ... only because some people will double click on a file without opening the project first and get frustrated if it doesnt have autocomplete.

Maybe I make it an option :)

**Comment by DDReaper** [comment]
Then I would say yes.  As VsCode doesn't have an option to "refresh" a file if it's open. hen yes it should sync prior to opening.
Also it should call "VSCode Open" before launching the file as well, ensuring that VSCode is open on the correct folder (that annoying thing where Unity can't pass the folder as a launch parameter)

**Comment by DDReaper** [comment]
P.S.
I'd also say that calling "Sync" should also call "Open" first.  Else you just end up with VsCode opening on the .sln without the folder

**Comment by reapazor** [comment]
I'll probably get to this tonight --- once the day job finishes up :)

I'll make it a toggle option "Open Project With File" and default it to on, or something like that, which also might dictate the need for an options sub-menu, we'll see.

**Comment by DDReaper** [comment]
Considering VsCodes dependencies, it would be the smart choice.
If you need any specific help, shout.  Obvious still a small project at the mo :dancer: 

Great work getting this kicked off btw
