### ISSUE TITLE
-CSharp.sln file is not generated

### ISSUE THREAD

**Issue by LuizThiagoDev** [dotBunny/VSCode#31]
Hello friends! I'm trying to use the VSCo desperately, but I could not make it work! My problem this time is that the -CSharp.sln file is not generated by Unity! Could anyone help me with this?
![captura de tela 2015-11-09 as 10 08 12](https://cloud.githubusercontent.com/assets/7306619/11033400/d2b1ec84-86c9-11e5-9402-253199b3fdf0.png)

**Comment by fishg** [comment]
Have you installed mono sdk download from here http://www.mono-project.com/download/ ?

**Comment by reapazor** [comment]
That does sound rather strange indeed, I would recommend updating to the latest version of the plugin and seeing what happens.
