### ISSUE TITLE
no Intellisense when in UnityEngine.UI

### ISSUE THREAD

**Issue by mengkheang** [dotBunny/VSCode#32]
the title say it all

**Comment by Taugeshtu** [comment]
Sooo, what OS, which VSCode and Unity versions?

**Comment by mengkheang** [comment]
on OS X 10.11 VSCode latest verion and Unity 5.2.2

**Comment by reapazor** [comment]
<img width="656" alt="screenshot 2015-11-23 11 50 40" src="https://cloud.githubusercontent.com/assets/99292/11343082/73fe50fa-91d8-11e5-96bb-616bc4000863.png">

(on OSX 10.11 with 5.2.2 and latest plugin)

I would check your project file to see if they are referenced in the solution/project, also see if Unity gives you any console errors about version mismatching with UnityEngine.UI.*
