### ISSUE TITLE
Plugin downloadable with unity below 5.2 form asset store.

### ISSUE THREAD

**Issue by bgtabtale** [dotBunny/VSCode#33]
I think the asset store only lets you download assets when you use unity versions that are equal or higher than the one you submitted the asset to the store with.
Since the asset was submitted using 5.2, anyone with a lower version can't download it.

I would be great if you can resubmit the asset with unity 4.6, so anyone with a version higher than that can get the asset from the store.

Thanks!

**Comment by reapazor** [comment]
I'll see about doing it for the next release, *tear* have to get a 4.x version again :)

**Comment by reapazor** [comment]
I'm going to set the bar at 4.6 ... unless someone has a request for earlier?
