### ISSUE TITLE
debugging broken by latest vs code update

### ISSUE THREAD

**Issue by shongololo** [dotBunny/VSCode#35]
The latest vs code update has broken debugging, but modifying line 815 of the vscode.cs file seems to fix it:
```
string fileContent = "{\n\t\"version\":\"0.2.0\",\n\t\"configurations\":[ \n\t\t{\n\t\t\t\"name\":\"Unity\",\n\t\t\t\"type\":\"mono\",\n\t\t\t\"request\":\"attach\",\n\t\t\t\"address\":\"localhost\",\n\t\t\t\"port\":" + port + "\n\t\t}\n\t]\n}";
```
Basically, the version number is updated and request:attach is added.

PS, extensions functionality is now available in vs code.

**Comment by reapazor** [comment]
Resolved in latest :) as for extension part ...yup I know :) and have some ideas.

**Comment by shongololo** [comment]
awesome, thanks.
