### ISSUE TITLE
Open C# Project in Code also open Visual Studio 2013

### ISSUE THREAD

**Issue by aaulia** [dotBunny/VSCode#36]
I understand that this might not happen on OSX (for obvious reason), but on Windows, with Visual Studio 2013/2010 installed. Every time I click on the menu entry, it opens Visual Studio 2013 and VSCode. Previously when MonoDevelop is installed, it would start MonoDevelop. Is this supposed to be this way (VSCode require one of these IDE to also open)? I already install Unity without MonoDevelop and uninstall the Microsoft Visual Studio Tools for Unity. I also tried resetting the preference, but it appears that Unity automatically detect if Visual Studio is installed on the system.

**Comment by aaulia** [comment]
Okay I just look at the code, so this is by design (calling Sync MonoDevelop Project first before calling VSCode). Sorry for the trouble. Should've done this first.

**Comment by reapazor** [comment]
There is a fix coming in Unity 5.3 for this I believe, it also removes my need to have a "Open in Code" option.
