### ISSUE TITLE
launch.json resetting its content to default when Unity enters Playmode

### ISSUE THREAD

**Issue by Utamaru** [dotBunny/VSCode#37]
I tried changing default Unity profile in "configurations" (by adding "request":"attach" line), adding custom profile, but every time I run project in Editor, launch.json resets to its default state.

Unity3D version: 5.2.1f1
OS: MacOS Yosemite 10.10.5.
VS Code version: 0.10.1 (issue was there before).

**Comment by reapazor** [comment]
Resolved with latest.
