### ISSUE TITLE
The Unity warning after save my code in VSCode.

### ISSUE THREAD

**Issue by x5lcfd** [dotBunny/VSCode#40]
![vscode_error](https://cloud.githubusercontent.com/assets/995277/11417205/c3e619da-944f-11e5-94e3-abe79e8bd383.png)

When I save my work in vscode, this error happend, and I must quit vscode and restart it again.

**Comment by reapazor** [comment]
I've seen this happen with MonoDevelop as well, i do not believe this specific to VSCode ... its basically a library is in use / referenced so it can't be overwritten by Unity.
