### ISSUE TITLE
Adds 3 question marks to start of VSCode.cs on updating

### ISSUE THREAD

**Issue by richy486** [dotBunny/VSCode#42]
On updating from version 2.2 to 2.3 when starting unity (not automatic update) VSCode.cs has '???' a the start of the file before the comment. The three question marks don't appear to be in the plugin repo.

**Comment by reapazor** [comment]
Can you attach a screen shot?

**Comment by richy486** [comment]
Go to unity properties and click Force Update
<img width="380" alt="bug1" src="https://cloud.githubusercontent.com/assets/631165/11484499/4677eda4-977c-11e5-8793-ce0ed238aa93.png">

Confirm
<img width="542" alt="bug2" src="https://cloud.githubusercontent.com/assets/631165/11484498/467775ae-977c-11e5-917d-c8daa5004aad.png">

Look at VSCode.cs in VSCode
<img width="705" alt="bug3" src="https://cloud.githubusercontent.com/assets/631165/11484500/467aa49a-977c-11e5-9d01-20b90466a4bf.png">

**Comment by reapazor** [comment]
That is damn strange for sure.

It basically just loads in https://raw.githubusercontent.com/dotBunny/VSCode/master/Plugins/Editor/VSCode.cs 

Which also doesn't show it.

Are you running a software firewall by chance?

**Comment by reapazor** [comment]
What OS?

**Comment by richy486** [comment]
OSX 10.11.1

**Comment by Shrike78** [comment]
Got same issue too. No particular firewall or other running. osx 10.10.5 (Yosemite)

**Comment by reapazor** [comment]
I haven't been able to reproduce this yet :/ 

Is your OS language different then english by chance?

**Comment by Shrike78** [comment]
Nope. I'm Italian but os language is set on english

**Comment by mjkkirschner** [comment]
same here

**Comment by reapazor** [comment]
try just replacing the file manually for now :( I haven't been able to repro this still ...i only have so many machines i can try on :(

**Comment by binarysqueeze** [comment]
I can confirm also. I have the latest OSX 10.11.1  and my machine is english, the only thing different is that I use a spanish keyboard.

Does that help?

**Comment by Souk21** [comment]
also having this issue, Mac OSX 10.9.5 (Language: French). I removed them by hand and everything works great.
Let me know if I can do some test for you :)

**Comment by reapazor** [comment]
I can finally say i was able to reproduce this :) So im workign on fixing it.
