### ISSUE TITLE
Win32 Exception

### ISSUE THREAD

**Issue by xCyborg** [dotBunny/VSCode#45]
I did everything like indicated in MS site, I'm on 0.10.3, Unity 5.3.0 and your latest package. I'm also using Unity's debugger package, I get the exception when I open a file or the C# project.

**Comment by xCyborg** [comment]
>Anything on *that***?**

**Comment by tommy-gun** [comment]
I have same problem here. Using Unity and VS Code on Ubuntu 15.04
This is stack trace:

Win32Exception: ApplicationName='code', CommandLine='"/mnt/b4bfaaa5-3fb3-44fe-b055-ea09420a39ba/Projects/unity-test/Roll-a-Ball" -r', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
dotBunny.Unity.VSCode.CallVSCode (System.String args) (at Assets/Plugins/Editor/VSCode.cs:309)
dotBunny.Unity.VSCode.MenuOpenProject () (at Assets/Plugins/Editor/VSCode.cs:504)

**Comment by tommy-gun** [comment]
Ok I from stack trace I found that I missing command code in my system.
I figured it out with this command
,,,
sudo ln -s /path/to/VSCode/Code /usr/local/bin/code
,,,

**Comment by chandujr** [comment]
Hey @tommy-gun can you please elaborate on that? I'm having the exact problem. But I'm on Windows. Is what you did adding path to the VSCode to the system path(Environment variable)?

**Comment by tommy-gun** [comment]
Hi @chandujr it is similar but not same for one important reason. My OS does not recognized command 'code' so, I make a symbolic link (with correct name) to it real location. 

Until this part it is same as add to PATH variable. But executable in VSCode dir is Code.exe (i supose, because in my case it is not .exe of course). So you must somehow set alias for this executable to desired command name 'code' with small letters.

**Comment by chandujr** [comment]
Thank you @tommy-gun I'll try that out.

**Comment by blorente** [comment]
Hey, any improvement on this? I am als orunning the WIN version and got hte same erro as the original poster

**Comment by bamncan** [comment]
I'm getting this issue, and I'm not sure where I can give it the full path to be sure?

Unity shows the option for external editor as: 

External Script Editor: code.cmd
External Script Editor Args: -r -g "$(File):$(Line)"

It doesn't appear as "VS Code".

**Comment by Prisoner19** [comment]
Hey, guys. I came across with the same problem and I managed to figure it out. 
Luckily, our friends from dotBunny put a text field with a path to code.cmd inside Edit/Preferences/VSCode.
By default, it is set as an inexistent folder inside AppData/Local. 
What I did was to set that path (line 52 in VSCode.cs) to:

var newPath = Path.GetPathRoot(System.Environment.SystemDirectory) + Path.DirectorySeparatorChar + "PROGRA~2" + Path.DirectorySeparatorChar + "MIFA7F~1" + Path.DirectorySeparatorChar + "bin" + Path.DirectorySeparatorChar + "code.cmd";

It is worth noticing that "PROGRA~2" is a denotation for Program Files (x86) and "MIFA7F~1" a denotation for Microsoft VS Code. You can get those names by going to C: in your cmd console and putting "dir /x". 

Good luck, buddies.

**Comment by jonnythelegend** [comment]
> var newPath = Path.GetPathRoot(System.Environment.SystemDirectory) + Path.DirectorySeparatorChar + "PROGRA~2" + Path.DirectorySeparatorChar + "MIFA7F~1" + Path.DirectorySeparatorChar + "bin" + Path.DirectorySeparatorChar + "code.cmd";

It is worth noticing that "PROGRA~2" is a denotation for Program Files (x86) and "MIFA7F~1" a denotation for Microsoft VS Code. You can get those names by going to C: in your cmd console and putting "dir /x".<

@Prisoner19 Thank you for your help! Your solution worked perfectly after I looked at the "dir /x" names of the directories.

For me (Fresh install of windows 10) "MIFA7F~1" is actually "MICROS~1". 

It may be different for each computer!

**Comment by michaeljota** [comment]
Well, now that Code it's installed in Program Files (x86), I think VSCode should do this by default.

**Comment by reapazor** [comment]
It should now :)

**Comment by reapazor** [comment]
Have you manually set the path in the options by chance? That seems to be the override for people when its not in a standard place?

**Comment by sotirosn** [comment]
How do you set the path in options?  I don't see anything in the Unity Preferences.

**Comment by sotirosn** [comment]
Ok so I guess the Force Update was not working as well.  I just copied and pasted the latest of of github's raw into the VSCode.cs and it works.  Thanks for writing this, because I hate using MonoDevelop!

**Comment by reapazor** [comment]
Np :)
