### ISSUE TITLE
Unity OSX Beachballing after attaching VSCode debugger.

### ISSUE THREAD

**Issue by paulbechard** [dotBunny/VSCode#46]
I had debugging working until one day unity just started freezing up / beachballing immediately after debug attach (with no breakpoints being hit). Has anyone else run into this issue?

**Comment by alwaysakil** [comment]
Same problem here... out of the blue, it takes ages to play any scene (new scene also) in the editor.

**Comment by reapazor** [comment]
I suspect this might have to do with Unity beta'n their own debug hook for VSCode, its an extension for Visual Studio Code, my goal is to make a one button install of it for the plugin (from the preferences). I worked a bit on it last weekend but ran into some hurdles. Looking to finish it up this weekend if possible.

**Comment by reapazor** [comment]
I'm going to close this now with the addition of the Unity Debugger side of things to the plugin. My suggestion is to use it :)
