### ISSUE TITLE
Change location of menu to be a main menu option, similar to UnityVS

### ISSUE THREAD

**Issue by DDReaper** [dotBunny/VSCode#5]
UnityVS and some other extensions have a top level menu option to highlight the functionality.

Instead of the current location:
Assets -> VSCode -> options

It should just be 
VSCode -> options

makes it cleaner and a lot easier to find for new users

**Comment by reapazor** [comment]
I really really REALLY wanted to do this, Unity however discourages main level menu items.  I'd like to respect their 'ideals' as best as possible.

**Comment by DDReaper** [comment]
Probably worth taking up with the VSCode guys to see what they can discuss with Unity then.

I know UnityVS and the Xbox tools are all main menu options.  As this is a potentially heavily used option it would make sense.

but I can also see the flip side putting it next to the "Sync MonoDevelop" option

**Comment by reapazor** [comment]
Indeed I have been talking with the Visual Studio Code team about many things :) 

I should probably be more specific... the Asset Store team has the policy of denying things that adjust the root menus. I'm pretty sure if a vendor like M$ said hey we want to put this tool up there wouldn't be a question.

One thing about the plugin is, once you turn it on, its my goal for you to never have to do anything else with it --- so having a root menu would be kinda of a waste.

**Comment by DDReaper** [comment]
Fair enough.
Although. Since Unity do not have a launch option / parameter for "Folder", you are always going to have to call open first (unless you call it prior to opening an asset "If" it's enabled.
