### ISSUE TITLE
No Intellisense

### ISSUE THREAD

**Issue by xCyborg** [dotBunny/VSCode#51]
Help me please, I think it has to do with CRX files and android extension namespace or omnisharpor something.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] The primary reference "UnityEditor.Android.Extensions" could not be resolved because it has an indirect dependency on the framework assembly "System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v2.0". To resolve this problem, either remove the reference "UnityEditor.Android.Extensions" or retarget your application to a framework version which contains "System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".

**Comment by natsumesou** [comment]
me too.
When I setup VSCode and Open C# Project in Code, The status bar of Visual Studio Code show no project loaded.
So Intelligente not work on my Visual Studio Code.

Unity 5.3.2f1
Visual Studio Code 0.10.6
VSCode 2.45
mono 4.2.1

**Comment by reapazor** [comment]
I'm closing this, not sure if its still happening, but mostly this was related to Code, not the plugin.
