### ISSUE TITLE
VSCode OmniSharp Startup Errors

### ISSUE THREAD

**Issue by slumtrimpet** [dotBunny/VSCode#54]
I've got a lot of Asset Store assets stored under my project's "Standard Assets" directory. (to speed up compiles)

When VSCode fires up OmniSharp I get a pile of errors like the following because evidently OmniSharp isn't looking inside the "Standard Assets" directory for code:

**[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The type or namespace name `TextMeshPro' could not be found. Are you missing an assembly reference?**

Assuming this is a bug, but please forgive if not.  Any ideas how to fix?

**Comment by slumtrimpet** [comment]
One more note... the code of course runs fine via Unity.  This is purely related to how OmniSharp is starting up.

**Comment by reapazor** [comment]
This problem relates to how the project files are created / used particularly how Visual Studio Code/OmniSharp uses them. I'm not sure I would say its quite a bug but more of a Unity does something special with its build order / structure and other compilers aren't quite there.

I've seen this myself in some projects :(
