### ISSUE TITLE
Omnisharp fails to load Editor-vs.csproj (on multiple unrelated projects)

### ISSUE THREAD

**Issue by RogueRocketGames** [dotBunny/VSCode#55]
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file '/Users/xyz/project/Assembly-CSharp-Editor-vs.csproj'.
/Users/xyz/project/Assembly-CSharp-Editor-vs.csproj

thought it might be project specific but now see it twice on 2 computers on different unity versions (4.6 vs 5.3), and 2 totally different projects from totally different companies.

What gives?  How do i debug?  there's no other issues related to that csproj listed in the output.

**Comment by reapazor** [comment]
Can you email me the project files (matthew [dot] davey @ dotbunny [dot] com). That sounds like a bug on the plugins part.

**Comment by foxxis** [comment]
Exact same problem here. But the actual file names seem to be the problem.
Code reports looking for the project files with a -vs suffix in the name i.e.:
Assembly-CSharp-vs.csproj
and so on for 4 files.
However, the files do exist in my project folder, but they lack the "-vs" suffix, i.e.:
Assembly-CSharp.csproj

So it is no wonder Code does not find what it is looking for and throws the following error:

[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from '/somepath/Assembly-CSharp-Editor-vs.csproj'.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file '/somepath/Assembly-CSharp-Editor-vs.csproj'.
System.ArgumentException: Project file somepath/Assembly-CSharp-Editor-vs.csproj not found
Parameter name: projectFileName

Any idea on how to solve this..? Thanks in advance!

**Comment by reapazor** [comment]
Well I just realized something, if you guys are seeing it looking for the -vs suffix, something is wrong as thats not in the latest version anymore... have you updated the plugin recently?

**Comment by foxxis** [comment]
You are right. In my case the cause was actually old project files that lingered in the project folder (switched project name and forgot to ditch the old files). So you are correct, once I deleted the old files, Code picked up the new file and correctly loaded the (sans -vs) csproj files.
