### ISSUE TITLE
Overloaded methods not supported in the expression evaluation of the debugger

### ISSUE THREAD

**Issue by zillix** [dotBunny/VSCode#56]
When debugging in VSCode while attached to Unity, attempting to invoke an overloaded method on an instance of a derived class will instead invoke the method on the parent class. During normal execution the correct method gets called. 
Note that this only occurs if the scoped instance is referenced by the parent type, rather than by the derived type.

public class Foo
{
    public virtual string getString() { return "foo"; }
}

public class Bar : Foo
{
    override public string getString() { return "bar"; }
}

public class Example
{
    Bar bar1 = new Bar();
    Foo bar2 = new Bar();
}

While debugging:
>bar1.getString()
>"bar"
>bar2.getString()
>"foo"
>((Bar)bar2).getString()
>"bar"

This may not be the fault of the plugin! However, it seems likely, as a similar fix had to be made to the now-obsolete UnityVS library: http://unityvs.com/documentation/changelog/

**Comment by reapazor** [comment]
Actually, i have a potential fix for this in the works.  "Hopefully" i'll get to it this weekend :)

**Comment by reapazor** [comment]
Turns out it has to do with Code :( *sigh*
