### ISSUE TITLE
namespace UnityEngine not found

### ISSUE THREAD

**Issue by Graham42** [dotBunny/VSCode#57]
VSCode can't seem to find any of the Unity references. When opening VSCode I get the warning message "Some projects have trouble loading. Please review the output for more details."

In the output:
```
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] The primary reference "System.Core",
which is a framework assembly, could not be resolved in the currently targeted framework.
".NETFramework,Version=v2.0". To resolve this problem, either remove the reference
"System.Core" or retarget your application to a framework version which contains
"System.Core".

[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] The primary reference "UnityEngine" could
not be resolved because it has an indirect dependency on the framework assembly
"System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which
could not be resolved in the currently targeted framework. ".NETFramework,Version=v2.0".
To resolve this problem, either remove the reference "UnityEngine" or retarget your
application to a framework version which contains "System.Core, Version=3.5.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089".
...
...
```

There's red squiggly underlines everywhere saying things like UnityEngine not found

System: Windows 7 Pro
Unity version: 5.3.1f1
Unity VSCode plugin version: 2.20-RELEASE
VSCode version:  0.10.6

**Comment by Graham42** [comment]
Manually changing `<TargetFrameworkVersion>v2.0</TargetFrameworkVersion>` to `v3.5` in "Assembly-CSharp.csproj" and "Assembly-CSharp-Editor.csproj" and then restarting VSCode seem to fix this.

**Comment by Graham42** [comment]
https://github.com/dotBunny/VSCode/commit/33dce457d3a7d8576206cede32d51c9b2ef2cc9d seems to have fixed this, but the code that I get from the unity asset store appears to be older? Perhaps need to update what's available from the asset store. Would be useful to use git tags to match Asset store versions to the repository

**Comment by reapazor** [comment]
*nod* I'll see about posting an updated version to the AS
