### ISSUE TITLE
Unity Editor debug launcher is removed when installing this from asset store

### ISSUE THREAD

**Issue by pflannery** [dotBunny/VSCode#59]
When using the [Debugger for Unity]( https://marketplace.visualstudio.com/items/Unity.unity-debug) and installing this script from the unity asset store then the launcher config:

```
{
    "version":"0.1.0",
    "configurations":[
        {
            "name":"Unity Editor",
            "type": "unity",
            "request": "launch",
        }
    ]
}
```

get replaced with 

```
{
	"version":"0.2.0",
	"configurations":[ 
		{
			"name":"Unity",
			"type":"mono",
			"request":"attach",
			"address":"localhost",
			"port":6068
		}
	]
}
```

which means debugging unity doesn't work with Windows.

The work around is to manually overwrite the launch config back to the [Debugger for Unity]( https://marketplace.visualstudio.com/items/Unity.unity-debug) launch config.

**Comment by pflannery** [comment]
I found the "Always write launch file" and unchecking that is easier than manually having to write the launch config every time..still would be nice if the launch config wasn't overwritten on install.

![image](https://cloud.githubusercontent.com/assets/1727302/12586089/cb3b5e56-c489-11e5-9e9f-41431be1b53b.png)

**Comment by reapazor** [comment]
I hate to be the bearer of bad news ... the UAS version isn't updated yet, its in review

When you have the "Use Unity Debugger" option turned on it will not overwrite the config (it will write the one the debugger wants and thats it). You don't need to worry about the always write flag really.

**Comment by pflannery** [comment]
@reapazor ah ok thanks.
