### ISSUE TITLE
No hover popups when debugging

### ISSUE THREAD

**Issue by Jasper76** [dotBunny/VSCode#60]
Debugging my Unity app works perfectly, except that I get no popups when I hover my mouse over any variable, including the variables that I want to debug.
As soon as I stop the debugging session, the hover popups work again.
I could look up the values of the variables in the Debug window, but that is way too much work.

Specs:
- Unity 5.3.1.f1
- Visual Studio Code 0.10.6
- Plugin 2.45

Is there a way I can resolve this?

**Comment by reapazor** [comment]
Win / Mac / Linux ?

And did you install the Unity Debugger extension?

**Comment by Jasper76** [comment]
Sorry, I'm working on a Mac, OS X El Capitan version 10.11.3.
Yes, the Unity Debugger is installed via de Unity settings screen. VS Code is giving me the message 'Debugger for Unity 1.01 is installed'. 'Use Unity debugger' checkbox is checked.

**Comment by dhesson** [comment]
This issue still exists in VSCode 0.10.8

**Comment by cesarvarela** [comment]
Came here from a google search. Is this releated to this plugin at all?

**Comment by reapazor** [comment]
It honestly most likely has to do with Rosilyn or the current .net compiler being used in Visual Studio Code, if the compiler has issues things don't work (like auto complete, intellisense, etc).

I don't have the bandwidth to debug issues like this atm ;/ but my hunch is to look at the compiler log and see what warnings can be found there.
