### ISSUE TITLE
Unity 5.5+ - VS Code Integration

### ISSUE THREAD

**Issue by reapazor** [dotBunny/VSCode#61]
Just thought I would put this out there so its not 'unexpected' ... Unity's plan is to support Code internally in the 5.5 release (we're talking at least half a year away). So when you select Code as your editor it will do everything the plugin does automatically.

I'm not sure this leaves much 'use' for the plugin at that point, the only thing I can think of really is the turning off code as editor on exiting/closing the project due to existing bugs in Code with large projects and not always being able to use it. I'll keep people posted in this thread as things develop.

Much like our MonoDevelop plugin of past, Unity does eventually pick up the torch, and it is a good thing.

**Comment by nfantone** [comment]
As of August 30, 2016, **UNITY 5.5.0B1** has been released with native support for VSCode

> Scripting: Built-in support for opening scripts in Visual Studio Code as an external script editor on OSX and Windows. Unity will now detect when Visual Studio Code is selected an external script editor and pass the correct arguments to it when opening scripts from Unity and setup a default .vscode/settings.json with file excludes, if it does not already exist.

You can check it out from https://unity3d.com/unity/beta

**Comment by reapazor** [comment]
Tis the day I've been waiting for, much like MonoDevelop before it, Unity has finally brought the communities work into the fold. 

We'll still keep this project available for legacy users, but support will be minimal if at all. It's been a crazy ride, seeing the uptake of the project has been incredible. Keep making awesome things ... I'm currently evaluating making a Rider Unity integration; you know because I can't not be making cool tools.

**Comment by Souk21** [comment]
(off-topic, sorry) @reapazor A Rider Unity integration would be so great!

**Comment by oxinosa** [comment]
@Souk21 That will be maybe the best news of the year !!!

**Comment by Gloomshroud** [comment]
I went into a new Unity 5.5.x install I did today on Windows 10. I made no assumptions and just tried to see if VS Code would work out of the box. It appears to do so, and the debugger seems to work too. 

Looks like your work has paid off, Reapazor. Well done, sir. You have run your race. You still looking at Rider integration?

**Comment by reapazor** [comment]
Much like our work with on support for MonoDevelop, eventually Unity integrates/catches up.

Actually Jetbrains has taken the torch for Rider: 
https://github.com/JetBrains/Unity3dRider

I've been working with them on an Unreal one for CLion, when I have time:
https://github.com/dotBunny/CLionSourceCodeAccess

**Comment by RubyGemer** [comment]
I'm using Unity 5.5.2f1. That doesn't support the plugin?
