### ISSUE TITLE
When Build Settings on Web Player, 'System.IO.File' error msg

### ISSUE THREAD

**Issue by hogganbeck** [dotBunny/VSCode#62]
Line 312, error CS0117: 'System.IO.File' does not contain a definition for 'ReadAllText'. I found a similar error [here](http://forum.unity3d.com/threads/system-io-file-does-not-contain-a-definition-for-createtext.146618/): 
and changed my build settings based on those comments. The problem cleared up. I'm on a Mac: 10.11.3.

**Comment by reapazor** [comment]
what version of mono?

**Comment by hogganbeck** [comment]
Forget I said anything. Had it in the wrong dir. Very embarrassing.
