### ISSUE TITLE
Open up the documentation from within Visual Studio Code

### ISSUE THREAD

**Issue by DarkMio** [dotBunny/VSCode#64]
Hi, there seems to be no current way to lookup the documentation instantly.

Given that Visual Studio (2015) does that by opening up an URL to the local docs with a search string attached, I think it should be possible to do the same for visual studio code.
In my personal opinion it would be perfectly fine if it opens to the user preferred browser - since I haven't seen that Visual Studio Code offers an inline browser view.

Thanks!

**Comment by reapazor** [comment]
Heh not a bad idea :) 

Long ago I did this for MD ... you might of struck a chord with me on this one :) ill see about this weekend.
