### ISSUE TITLE
Unity 5.3.2p2 - freezing on project open and run

### ISSUE THREAD

**Issue by bitwise-github** [dotBunny/VSCode#66]
Using Unity 5.3.2p2, VSCode 2.45, OSX El Capitan:
-Unity freezes when opening project
-Unity freezes when pushing play
-Freeze is not permanent, just very long.

Tried:
-Force updated VSCode
-Restarted computer

-Disabling VSCode integration stops the freezing.

**Comment by DarkMio** [comment]
This seems to be due to a buggy updater:

http://i.imgur.com/lQoeVIv.png

I have the exact same issue, just with the window displaying it. It's very annoying and the updater comes up every second or third time I try to playtest my game.

**Comment by bitwise-github** [comment]
The problem seems to have subsided...So I'm wondering if I had something opened that was holding onto some resource in a way the VSCode plugin hadn't expected. I haven't updated VSCode, this plugin, or Unity since the problem started, so I'm at a bit of a loss =/

**Comment by Impmaster** [comment]
I get this too. Very annoying. I'm on windows 10. I literally did nothing but install VS Code from the assets store and it wont run properly.

**Comment by bitwise-github** [comment]
I've tried to turn off editor attaching, but the setting won't stick, and keeps re-enabling itself when I restart Unity. I'm not sure if this is part of the problem, or if this extension is causing it directly.

**Comment by reapazor** [comment]
I've been following this problem for a while now, and am honestly not sure of whats going on.

Maybe its because i havent pushed an update to the UAS version of the plugin, but on latest in 5.3.2f1 i don't seem to have this problem myself, and I spent about 8 hours a day in that version alone.

Are there any other exceptions or errors in the Unity log?
