### ISSUE TITLE
Omnisharp Error (yeah I know, another one...)

### ISSUE THREAD

**Issue by JohlyDragon** [dotBunny/VSCode#68]
The error is weird, I'll post the whole output: (I don't really get it but it says i don't have a solution file but i'm pretty sure i do, I also don't get this "and have specified a non-default Configuration or Platform that doesn't exist for this project." so please explain it. I really want to use visual studio code as its lightweight and stuff.)

[INFO] Starting OmniSharp at 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\2D Adventure Platformer Project (W.I.P).sln'...
[INFO] Started OmniSharp from 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\bin\omnisharp.cmd' with process id 12016...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)' on host 9120.
[ERROR:OmniSharp.Dnx.DnxPaths] The specified runtime path 'default' does not exist. Searched locations C:\Users\apalb_000\.dnx\runtimes\dnx-clr-win-x86.default
C:\Users\apalb_000\.dnx\runtimes\kre-clr-win-x86.default
C:\Users\apalb_000\.dnx\packages\KRE-CLR-x86.default
C:\Users\apalb_000\.k\runtimes\dnx-clr-win-x86.default
C:\Users\apalb_000\.k\runtimes\kre-clr-win-x86.default
C:\Users\apalb_000\.k\packages\KRE-CLR-x86.default
C:\Users\apalb_000\.kre\runtimes\dnx-clr-win-x86.default
C:\Users\apalb_000\.kre\runtimes\kre-clr-win-x86.default
C:\Users\apalb_000\.kre\packages\KRE-CLR-x86.default.
Visit https://github.com/aspnet/Home for an installation guide.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No project.json based projects found
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Detecting projects in 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\2D Adventure Platformer Project (W.I.P).sln'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-firstpass.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-firstpass.csproj
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The OutputPath property is not set for project 'Assembly-CSharp-firstpass.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='MCD'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-firstpass.csproj'.
c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-firstpass.csproj

[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp.csproj
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The OutputPath property is not set for project 'Assembly-CSharp.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='MCD'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor-firstpass.csproj'.
c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp.csproj

[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor-firstpass.csproj
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The OutputPath property is not set for project 'Assembly-CSharp-Editor-firstpass.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='MCD'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor-firstpass.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor.csproj'.
c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor-firstpass.csproj

[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor.csproj
[ERROR:OmniSharp.MSBuild.MSBuildProjectSystem] The OutputPath property is not set for project 'Assembly-CSharp-Editor.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='MCD'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.
[WARNING:OmniSharp.MSBuild.MSBuildProjectSystem] Failed to process project file 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor.csproj'.
c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)\Assembly-CSharp-Editor.csproj

[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'c:\Users\apalb_000\Desktop\Homey\Unity Projects\Arcade-Style Games\2D Adventure Platformer Project (W.I.P)'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading

**Comment by ellipticaldoor** [comment]
I also get the error Failed to process project file '../Assembly-CSharp.csproj'. Maybe the fault is on how Unite creates this file?

**Comment by sorab2142** [comment]
The C# extension got updated and removed Unity .csproject support so install the Legacy C# Extension in Code, NOTE: Remove the old C# extension before attempting to install the Legacy one.

**Comment by reapazor** [comment]
see #104
