### ISSUE TITLE
Intenseness does not work in .cs files with #if's regardless of value of script define

### ISSUE THREAD

**Issue by gotomgo** [dotBunny/VSCode#69]
#if UNITY_IOS
public static void IntellisenseNotWorkingHere() {
    ///
}
#endif

Are the script defines passed from Unity to VS Code?

**Comment by gotomgo** [comment]
So, after switching platforms and restarting VS Code it worked as expected, so that is reasonably good news. Still, I don't want to have to re-start VS Code; better to have it auto-restart if the primary configuration of the project has changed. 

Just for the record since it is related (scripting defines) files/code that is NOT active is displayed normally. VS Code must have a mechanism for showing it as not in use? Should figure out how to trigger that. or maybe suggest to user how to configure/change theme in this regard

**Comment by reapazor** [comment]
When the project file is written by unity the defines are outputted, then the project file is converted to one for VSCode ... without that project file changing it can't happen. 

Out of my hands :(
