### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by reapazor** [dotBunny/VSCode#7]
This is more of a reminder to create the required features for linux support, which should have mono debugging! yay!

**Comment by cra0zy** [comment]
Tried out this extension on Linux and some fast notes:
 - did manage to make Unity open up VSCode, of course with modifications to script
 - checkboxes in the mainmenu weren't visible, Unity is in experimental build for Linux so totally expected a bug, just need to remember to report this bug later
 - wasn't able to get debugging working

Just curious, why would someone choose VS Code over MonoDevelop / Xamarin Studio, what does it offer that the other one doesn't?

**Comment by reapazor** [comment]
- What sorts of changes were needed to get VSCode to open? 
- As for the checkboxes, yes, thats a newer feature in Unity.
- Word from the VSCode team is that debugging for unity, specifically the hang is fixed in their next drop.
- Can you point me to where I skipped?

VSCode is just a lot cleaner, and faster IMHO. It just feels better then MD.

**Comment by cra0zy** [comment]
> What sorts of changes were needed to get VSCode to open?

I personally added a script to /usr/bin/code that points to VSCode and added #if UNITY_EDITOR_WIN for the current else, and added new else for Linux editor

> Word from the VSCode team is that debugging for unity, specifically the hang is fixed in their next drop.

Sweet

> Can you point me to where I skipped?

It was one of the options under "Additional Options" that had it skipped

**Comment by cra0zy** [comment]
> VSCode is just a lot cleaner, and faster IMHO. It just feels better then MD.

I have an SSD so both launch as fast for me, as for being cleaner... this is not something debatable, we all have styles that we like, tho I'll give a point to VS Code for having a nice light and dark themes, unlike MD which only has light theme with themable editor.

As for my original question, VS Code doesn't seem to offer anything besides brand name and dark theme when compared to MD, do tell me if I missed something.

**Comment by n0f3** [comment]
it has some nice features that are not available on mono, such as being able to view multiple tabs at once, display spacing characters in editor, etc.
It is also much lighter weight compared to mono, more stable/lean.

But as you said it's up to personal preference really.

**Comment by cra0zy** [comment]
> being able to view multiple tabs at once

MD has that....

> display spacing characters in editor

doesn't have that tho

**Comment by cra0zy** [comment]
Ok, I found something that VSCode does better than MD, C# 6

**Comment by reapazor** [comment]
MD has rendering of white space characters, as does VSCode.

**Comment by cra0zy** [comment]
> rendering of white space characters

Ok, so maybe I misunderstood what it means, so.... what does it mean?

**Comment by cra0zy** [comment]
With the newest Unity Linux build I managed to get debugging working as well :D

**Comment by reapazor** [comment]
Just a heads up, I saw your pull request -- i already have a working set of most of these changes in my local.

I'll go over and make sure i didnt miss anything before i commit mine.

**Comment by cra0zy** [comment]
I saw that you added your Linux support thingy, I'll modify my PR accordingly.

**Comment by cra0zy** [comment]
Also close down the PR once you are done taking stuff from it.

**Comment by reapazor** [comment]
I'm gonna close this one now that it's in the main line.
