### ISSUE TITLE
Not opening on new VS Code 0.10.10 (February 2016)

### ISSUE THREAD

**Issue by AndersonDev** [dotBunny/VSCode#70]
Hi, I just updated to new VS Code 0.10.10 (February 2016). And took this error:

![err](https://cloud.githubusercontent.com/assets/6890368/13598518/d32c970c-e526-11e5-88ef-7ea954b3c648.png)

I tried to fix but I had no success(

**Comment by CanisLupus** [comment]
I can confirm that this also happens here. No clue to what causes the problem, though the new VSCode version does require us to download C# language support and the Mono Debug from the marketplace (they don't come bundled with the program). Not sure if that is at all related. It shouldn't be.

**Comment by iRhyiku** [comment]
Same error here, downgrading also seems to not fix it for some reason, even after a removing all of VS Code.

**Comment by animanoir** [comment]
Was about to post it. Exactly the same error.

```
Win32Exception: ApplicationName='code', CommandLine='"C:/Users/oscar/Documents/Unity/zombis" "C:/Users/oscar/Documents/Unity/zombis\Assets/Scripts/Prueba.cs" -r', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
dotBunny.Unity.VSCode.CallVSCode (System.String args) (at Assets/VSCode/Plugins/Editor/VSCode.cs:360)
dotBunny.Unity.VSCode.OnOpenedAsset (Int32 instanceID, Int32 line) (at Assets/VSCode/Plugins/Editor/VSCode.cs:794)
UnityEditor.DockArea:OnGUI()
```

**Comment by sorab2142** [comment]
Same error here.

**Comment by spiphy** [comment]
I am getting the same crash.  If I open PowerShell or a cmd window and run code with the same arguments listed in the exception everything works fine.

**Comment by realtreat** [comment]
Thanks a lot for the fix

**Comment by iRhyiku** [comment]
Fix worked great, thanks!
