### ISSUE TITLE
error: spawn mono ENOENT. Stopping the debug adapter.

### ISSUE THREAD

**Issue by orrgal1** [dotBunny/VSCode#74]
i get this when trying to run the debugger. i have unity open and used the "Open C# project in Code" menu to open VSCode. also, i have followed all the instructions on installing the VSCode plugin (from UAS). the only thing i am still in the process of doing is installing mono (brew install mono).

**Comment by orrgal1** [comment]
yes, installing mono solved it

**Comment by DeanHH** [comment]
I have already get MonoDevelop installed by unity.Should I have to do (brew install mono)?

**Comment by newgrounds** [comment]
Running `brew install mono` fixed it for me.
