### ISSUE TITLE
Strange character on line 18

### ISSUE THREAD

**Issue by bitwise-github** [dotBunny/VSCode#75]
https://github.com/dotBunny/VSCode/blob/8a60bde4dfe3213db0c40398f74dffeb56c84fa6/Plugins/Editor/VSCode.cs#L18

There is some wierd character at the end of line 18. Every time I update VSCode from Unity, it turns into "??". Could someone please remove it?

**Comment by reapazor** [comment]
The ?? seems to be from bad characters forming when it downloads an update from GitHub. I've still trying to figure out whats causing them :(

**Comment by bitwise-github** [comment]
Sorry...it looks like aogden did a pull request that already removed the characters. Maybe I should close this then?

https://github.com/dotBunny/VSCode/pull/76

**Comment by reapazor** [comment]
I unno, leave her open, i need to figure out why the extra 'crap' gets added when grabbing from GitHub's raw addresses. I highly suspect its on the .net stream end though ;/

**Comment by bitwise-github** [comment]
I don't think it's an artifact from Github.. It seems like someone accidentally input some kind of Unicode character into the file. The pull request I cited above(#76) seems to have removed the character. I haven't updated VSCode since then, but I assume the problem will be fixed.

Possible causes:
-Accidental Alt+Key combo in windows creating a unicode character
-copying code from a webpage and accidentally bringing strange characters along
-pasting code to/from a text editor with auto formatting features like educated-quotes, etc..
-corruption of the file(unlikely, i think)

I'll leave it to you to close this, but I think it should be ok.

**Comment by bitwise-github** [comment]
Just updated..seems fine.
