### ISSUE TITLE
Not opening on new VS Code 0.10.11 (Windows build) with plugin v2.47

### ISSUE THREAD

**Issue by forthtaken** [dotBunny/VSCode#78]
There is Wind32 exception indicating it was looking for VS code bin installation on directory which is not matching my actual installation path (C:\Program Files (x86)\Microsoft VS Code\bin).

Easy workaround can be applied but tweaking the 'newPath' variable specified UNITY_EDITOR_WIN.
Sorry I am just new here. Just to post this issue in case anyone has similar issue and make author aware.

Brian

Detail
==============================
Win32Exception: ApplicationName='C:\Users\brian_liao\AppData\Local\Code\bin\code.cmd', CommandLine='"D:/MyProject" -r', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
dotBunny.Unity.VSCode.CallVSCode (System.String args) (at Assets/Plugins/Editor/VSCode.cs:383)
dotBunny.Unity.VSCode.MenuOpenProject () (at Assets/Plugins/Editor/VSCode.cs:669)

**Comment by dkoprowski** [comment]
I also faced this issue. Plugin points to AppData\Local folder and my VS Code is default installed in Program Files

**Comment by Utamaru** [comment]
Same issue.

`Win32Exception: ApplicationName='code', CommandLine='"F:/Projects/project" -r', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
dotBunny.Unity.VSCode.CallVSCode (System.String args) (at Assets/VSCode/Plugins/Editor/VSCode.cs:360)
dotBunny.Unity.VSCode.MenuOpenProject () (at Assets/VSCode/Plugins/Editor/VSCode.cs:646)`
