### ISSUE TITLE
Cannot convert `UnityEngine.GUIContent' expression to type `string'

### ISSUE THREAD

**Issue by cdes** [dotBunny/VSCode#79]
```
Assets/Plugins/Editor/VSCode.cs(699,40): error CS1503: Argument `#1' cannot convert `UnityEngine.GUIContent' expression to type `string'

Assets/Plugins/Editor/VSCode.cs(699,40): error CS1502: The best overloaded method match for `UnityEditor.EditorGUILayout.DelayedTextField(string, string, UnityEngine.GUIStyle, params UnityEngine.GUILayoutOption[])' has some invalid arguments

Assets/Plugins/Editor/VSCode.cs(699,40): error CS0122: `UnityEditor.EditorGUILayout.DelayedTextField(string, string, UnityEngine.GUIStyle, params UnityEngine.GUILayoutOption[])' is inaccessible due to its protection level

```

Here's the line:
`CodePath = EditorGUILayout.DelayedTextField(new GUIContent("VS Code Path", "Full pah to the Micosoft Visual Studio code executable."), CodePath);
`
I've changed it to this and the problem is gone:
`CodePath = EditorGUILayout.TextField(new GUIContent("VS Code Path", "Full pah to the Micosoft Visual Studio code executable."), CodePath);`

**Comment by reapazor** [comment]
Are you using 4.x?

**Comment by cdes** [comment]
Yes

**Comment by reapazor** [comment]
ya :( my bad i should of wrapped that ... 4x doesnt like that overload... will fix :)

**Comment by zemos** [comment]
This is also happening in Unity 5.2
