### ISSUE TITLE
not work with Unity 5.4b11

### ISSUE THREAD

**Issue by nestg** [dotBunny/VSCode#81]
this is the console log

Win32Exception: ApplicationName='C:\Users\user1\AppData\Local\Code\bin\code.cmd', CommandLine='"C:/ant/ant5" -r', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
dotBunny.Unity.VSCode.CallVSCode (System.String args) (at Assets/VSCode/Plugins/Editor/VSCode.cs:382)
dotBunny.Unity.VSCode.MenuOpenProject () (at Assets/VSCode/Plugins/Editor/VSCode.cs:668)

**Comment by reapazor** [comment]
Looks like you need to set the manual path to code, could a bunch of windows people maybe post their paths.

If there is a trend we probably could change the default path for windows to it.

**Comment by vncastanheira** [comment]
Setting the full path worked on Windows.
`proc.StartInfo.FileName = @"C:\Program Files (x86)\Microsoft VS Code\Code.exe";`

But that's odd, because at the same time I could call Code trought cmd
