### ISSUE TITLE
Maybe errata? Cannot change path of VSCode

### ISSUE THREAD

**Issue by MintX** [dotBunny/VSCode#82]
I could't change path of VSCode, so I investigated VSCode.cs.

I think... on Line 60,
`EditorPrefs.GetString("VSCode_CodePath", value);`
must be 
`EditorPrefs.SetString("VSCode_CodePath", value);`
right?

After editting this, I can change path, and VSCode launched successfully.

**Comment by reapazor** [comment]
*doh*

**Comment by MintX** [comment]
Thanks for immediate patch!!

**Comment by reapazor** [comment]
Thank you for pointing it out!
