### ISSUE TITLE
For those who have Win32Exception in System.Diagnostics.Process.Start ()

### ISSUE THREAD

**Issue by rumyancevpavel** [dotBunny/VSCode#83]
In **VSCode.cs** file replace** CodePath** property with following code:

public static string CodePath
        {
            get
            {
                // ! Path to your code.cmd
                return @"C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd";
            }
            set
            {
                EditorPrefs.SetString("VSCode_CodePath", value);
            }
        }

**Comment by reapazor** [comment]
Is this the new 'home' of the latest version?  could just set the default / etc

**Comment by rumyancevpavel** [comment]
I suppose yes... I've just installed VS Code and it has been installed in this folder
