### ISSUE TITLE
Does not work under Fedora Linux

### ISSUE THREAD

**Issue by brandex07** [dotBunny/VSCode#85]

**Comment by yedpodtrzitko** [comment]
hi,
could you provide any details what exactly "does not work"?

**Comment by vicricker** [comment]
It works, but it's a bit of a mess.  It shows many errors on code that works.  I'm a noob at C#, so this may be trivial, for example,

` public class Whatever : MonoBehaviour {
`
Whatever and MonoBehavior are flagged as errors.

Hovering over Whatever shows:

Predefined type 'System.Void' is not defined or imported [Assembly-CSharp]
Whatever

Hovering over MonoBehavior gives:

The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. [Assembly-CSharp]
UnityEngine.MonoBehaviour

Other crazy stuff is broken like:
    bool turn = true;

Predefined type 'System.Boolean' is not defined or imported [Assembly-CSharp]

**Comment by reapazor** [comment]
This sounds like an issue with pathing to the reference libraries ...i spun up an ubuntu vm the other day so I'll see about installing a copy of Unity on it to see if i see anything immediate.

**Comment by vicricker** [comment]
Thanks!  most appreciated.  What's odd is the code completion/assist seems to work fine, at least as far as I've used it.  Also, I'm using Unity 5.4beta if that matters.

If I can do anything to help, let me know.

**Comment by mseqs** [comment]
Did you installed the additional mono assemblies? Try installing mono-complete package (mono-project site explains how in Fedora) which installs all additional assemblies and such

**Comment by reapazor** [comment]
I'm closing the ticket due to inactivity :/ reopen with details 👯

**Comment by rahul-sinha1908** [comment]
Same thing is happening with me. If someone found out the solution please help me out too.
