### ISSUE TITLE
Omnisharp shows 0 projects -- Intellisense not working

### ISSUE THREAD

**Issue by richcollins** [dotBunny/VSCode#86]
The OmniSharp projects icon (https://code.visualstudio.com/Docs/runtimes/unity#_common-questions) is missing from the vs code status bar.  When I run the OmniSharp: Select Project command it says: "There are no entries to pick from.

This is Unity 5.3.4f1 and Visual Studio Code 0.10.11.

**Comment by okuligowski** [comment]
Same for me :/
Unity 5.3.2f1, VSCode 0.10.11

**Comment by reapazor** [comment]
Ahh yes :) I originally had them hidden as well -- till everything exploded.

**Comment by richcollins** [comment]
Thanks that was the problem.
