### ISSUE TITLE
latest version causes errors in Unity 5.2

### ISSUE THREAD

**Issue by HawkenKing** [dotBunny/VSCode#87]
I get the following errors (need to use 5.2, for a reason)

> Assets/VSCode/Plugins/Editor/VSCode.cs(700,40): error CS1503: Argument `#1' cannot convert `UnityEngine.GUIContent' expression to type `string'

>Assets/VSCode/Plugins/Editor/VSCode.cs(700,40): error CS1502: The best overloaded method match for `UnityEditor.EditorGUILayout.DelayedTextField(string, string, UnityEngine.GUIStyle, params UnityEngine.GUILayoutOption[])' has some invalid arguments

>Assets/VSCode/Plugins/Editor/VSCode.cs(700,40): error CS0122: `UnityEditor.EditorGUILayout.DelayedTextField(string, string, UnityEngine.GUIStyle, params UnityEngine.GUILayoutOption[])' is inaccessible due to its protection level

**Comment by reapazor** [comment]
This is because of an API/Feature change with Unity, I'll see about fixing this in the repo at some point today --- i'll just have it check if were 5_3 + ?
