### ISSUE TITLE
Error getting response stream 

### ISSUE THREAD

**Issue by Gpef** [dotBunny/VSCode#89]
[VSCode] Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
UnityEngine.Debug:Log(Object)
dotBunny.Unity.VSCode:CheckForUpdate() (at Assets/Plugins/Editor/VSCode.cs:384)
dotBunny.Unity.VSCode:.cctor() (at Assets/Plugins/Editor/VSCode.cs:258)
UnityEditor.EditorAssemblies:SetLoadedEditorAssemblies(Assembly[])

Also when i trying to load scrpit (double click on it) unity opens Mono instead of Code and error log has next message:

Win32Exception: ApplicationName='code', CommandLine='"E:/path to my project folder" "E:/path to my project folder\Assets/Scripts/Game/Field/GameInfo.cs" -r', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
dotBunny.Unity.VSCode.CallVSCode (System.String args) (at Assets/Plugins/Editor/VSCode.cs:360)
dotBunny.Unity.VSCode.OnOpenedAsset (Int32 instanceID, Int32 line) (at Assets/Plugins/Editor/VSCode.cs:794)
UnityEditor.DockArea:OnGUI()

code 1.0.0
unity 5.1.1.f1

Help please

**Comment by reapazor** [comment]
I think it was pointed out by someone else, that particular version of Unity has a mono implementation that doesn't support SSL (https) and causes errors.

**Comment by Gpef** [comment]
@reapazor thx for reply! what version of unity should i use?

**Comment by reapazor** [comment]
Try updating to latest? 5.3 is latest public release.
