### ISSUE TITLE
The type or namespace name 'Xcode' does not exist in the namespace 'UnityEditor.iOS'

### ISSUE THREAD

**Issue by heshuimu** [dotBunny/VSCode#91]
I was using a plugin in my project which has a build post processor. 

When VSCode loaded the project, it showed an error on the line

`using UnityEditor.iOS.Xcode;`

saying:

> The type or namespace name 'Xcode' does not exist in the namespace 'UnityEditor.iOS' (are you missing an assembly reference?) [Assembly-CSharp-Editor]

However, in Unity, build was successful. Is there any way to let VSCode recognize this namespace?

I was using Unity 5.4.0b15 on El Capitan with latest VSCode and VSCode plugin.

**Comment by reapazor** [comment]
I only have b14 installed on this computer, but i had a peak and it doesn't look like there is a class or namespace under UnityEditor.iOS. Also online docs seem to support that, of course it could have been added in b15, ill probably install it tomorrow.

Are you sure that the precompile conditions aren't causing an ignore of that line? 

Can anyone confirm/deny that is added in beta 15? Is there a library adding it outside of the standard unity libraries.

**Comment by heshuimu** [comment]
So, to elaborate, the code looks like this in the file:

```
#if UNITY_5 && (UNITY_IOS || UNITY_TVOS)
using UnityEditor.iOS.Xcode;
#endif
```

The building target was set as iOS so this precompile conditions included this. If the build target is set as Android this error disappears. 

Actually there is a class in the code that seems to rely on that namespace: 

```
#if UNITY_IOS
#if UNITY_5
...
PBXProject project = new PBXProject();
...
#endif
#endif
```

Actually I did a google search and I found this class description located in the online scripting reference. Looks like the Xcode.iOS namespace is also shown there. 

(http://docs.unity3d.com/540/Documentation/ScriptReference/iOS.Xcode.PBXProject.html)

**Comment by reapazor** [comment]
Interesting, mainly because i don't find it in auto complete either ... with b15 installed. 

So I did some digging ... specifically looking at the oddities of that namespace, since it is not part of the core Unity it is actually located in the playback libraries specifically for iOS (UnityEditor.iOS.Extensions.Xcode). That being said, it looks like you might have to manually include that into your project?

Does Unity maybe include it during its compile? Does it show up in a mlnodevelop project if you look there? Have a search in your project file to see if its in there ... if its not that will give me a place to start ie am i cutting it out by accident, or is unity just not giving it to us.

**Comment by heshuimu** [comment]
Unfortunately, I tried "Build All" in MonoDevelop, and it also gave out the "namespace 'Xcode' does not exists" error, even though the C# file is in Assembly-CSharp-Editor.csproj. 

Another thing I found is that IntelliSense in both VSCode and MonoDev could not even show "iOS" namespace in the auto complete when I enter"using UnityEditor."

**Comment by reapazor** [comment]
Ya, it sounds like Unity includes that manually in their own compilation pass.

One possible option is that I could detect the platform and include it based on the relative path to Unity, but that seems 'backwards'. Unity should be including it on their own project creation. I'm going to send this along the chain.

**Comment by reapazor** [comment]
Unity has acknowledged this as a problem and has passed it on for resolution within their development team. Unfortunately, no-one knows when a resolution will be in place :(

**Comment by heshuimu** [comment]
It is good to know that it is a bug, not something Unity intentionally did to restrict accesses. 😆 Thanks for doing that. 
Do they have a bug report of this to track progresses??

**Comment by reapazor** [comment]
793624

I would paste the actual link, but the whole back history is visible for my account with them at that point and sadly, thats not something I wish to share :) its been quite a few years LOL
