### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by cyllu2** [dotBunny/VSCode#92]

**Comment by reapazor** [comment]
Justin Beiber is that you?

All jokes aside, if something isn't working remove the VSCode script file and it won't have anything to do with your project.

I suspect your using the old UAS version that takes forever to get updated. Still waiting for an update approval on that end.

**Comment by cyllu2** [comment]
No idea what UAS is. I'm literally creating a new project now, downloading the package from the asset store, going to preferences to enable the shitty thing, and then trying to open a script. Bam! Errors galore.
