### ISSUE TITLE
Option to use Code's Insider version

### ISSUE THREAD

**Issue by johanneskopf** [dotBunny/VSCode#93]
Implement an option (a switch) in the settings to use Code's Insider version instead of the usual.
Therefore change the path to:
`var newPath = ProgramFilesx86() + Path.DirectorySeparatorChar + "Microsoft VS Code Insiders" + Path.DirectorySeparatorChar + "bin" + Path.DirectorySeparatorChar + "code-insiders.cmd";`
And refresh the "VSCode_CodePath" Editor prefs.

That would be great if you can implement that feature.

**Comment by reapazor** [comment]
Why not manually set the path to that :) (in preferences)
