### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by cadupedroni** [dotBunny/VSCode#94]
I'm trying to save a file that you need permission to be saved, but I'm not the vscode this option. For example in the sublime text he presents a modal requesting my password to allow me to save this file.

I have how to do the same in the vscode?

error
Failed to save 'hosts': A system error occured (EACCES: permission denied, open '/private/etc/hosts')

**Comment by reapazor** [comment]
This would be more likely handed by code itself, you may want to file a ticket over @ [https://github.com/Microsoft/vscode] (https://github.com/Microsoft/vscode)

As this is a system file change you might be able to find a plugin to support sudo levelling, but I'm not sure.
