### ISSUE TITLE
No Syntax Highlighting

### ISSUE THREAD

**Issue by leissler** [dotBunny/VSCode#95]
I use a Mac (El Capitan) with Unity 5.3.4f1 and tried to integrate VSCode using the plugin.
When double-clicking a C# script file in Unity, VSCode opens with the correct source file and the solution but there is no syntax highlighting.

![image](https://cloud.githubusercontent.com/assets/243927/15149936/bea420e4-16cb-11e6-9cba-9a0ff74f2f64.png)

Also the auto-completion features for Unity specific stuff doesn't work at all. I'm sure I had this running a couple of weeks ago but now it just refuses.

**Comment by reapazor** [comment]
It looks like VSCode isn't detected CSharp as a type ... you now have to install C-Sharp as a language extension with the new versions of Code.

https://code.visualstudio.com/Docs/languages/csharp

**Comment by leissler** [comment]
Thanks. Well spotted.
That did the trick!

**Comment by raldred** [comment]
Does this completely fix everything including Omnisharp? I have same issue on fresh El Cap install.
Installed C# extension, highlighting is fixed but there's no autocomplete. Omnisharp is running

    [INFO] Starting OmniSharp at '/Users/robaldred/Dropbox (Personal)/Dev/Games/Unity/Bare/Bare.sln'...
    [INFO] Started OmniSharp from '/Users/robaldred/.vscode/extensions/ms-vscode.csharp-1.0.10/.omnisharp/OmniSharp' with process id 57341...
    OmniSharp: -s /Users/robaldred/Dropbox (Personal)/Dev/Games/Unity/Bare/Bare.sln --hostPID 57319 dnx:enablePackageRestore=false --stdio
    [INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/Users/robaldred/Dropbox (Personal)/Dev/Games/Unity/Bare/Bare' on host 57319.
    [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/robaldred/Dropbox (Personal)/Dev/Games/Unity/Bare/Bare
    [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: True
    [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
    [INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
    [INFORMATION:OmniSharp.Startup] Configuration finished.
