### ISSUE TITLE
[OSX] No intellisense, strange editor path?

### ISSUE THREAD

**Issue by raldred** [dotBunny/VSCode#97]
I've just done a fresh install of OSX El Cap.
Unity 5.3.4f1 
VSCode latest 1.1.1 (13th May)
Running the latest 2.6 Release of plugin

Editor path for preferences has as weird path for Code.
Plugin keeps prompting for debugger install even though I have it installed.

External tools preferences
![External tools preferences](https://www.dropbox.com/s/2hpgfueabtvzt4j/Screenshot%202016-05-18%2015.22.46.png?dl=1)

VSCode preferences
![VSCode preferences](https://www.dropbox.com/s/u79ra8l746q7rd0/Screenshot%202016-05-18%2015.20.47.png?dl=1)

Extensions Installed
![Extensions Installed](https://www.dropbox.com/s/eht40gdzrbkg9em/Screenshot%202016-05-18%2015.23.41.png?dl=1)

Debugger installed
![Debugger installed](https://www.dropbox.com/s/am35yli4lg41a3x/Screenshot%202016-05-18%2015.30.34.png?dl=1)

Tried reinstalling everything & cleaning out .csproj & .sln files can't get intellisense to work.
I notice there's no -CSharp.sln being generated?

Project folder
![Project folder](https://www.dropbox.com/s/cuhy0h3lb9mw5vf/Screenshot%202016-05-18%2015.25.45.png?dl=1)

I had everything working nicely on Yosemite but needed upgrade to El Cap for latest XCode & I always do a fresh OS install instead of an update.

Any suggestions much appreciated

**Comment by Souk21** [comment]
[It's because of the new C# extension version.](https://github.com/OmniSharp/omnisharp-vscode/issues/331)

You can just uninstall "C# Extension" for the moment, and re-instal the old "Built-in Omnisharp" which should work.

**Comment by seanmcbreen** [comment]
Thats right we apologize for this - we have added some additional context re: this to the VS code unity page.  We  are also working with the C# team to ensure support is added to the new C# plug-in.

[Updated doc for VS Code and Unity](http://code.visualstudio.com/docs/runtimes/unity)

cc' @reapazor 

Sean
-VS Code Core Team Member

**Comment by corum** [comment]
Same issues here but, at the moment of writing, it seems impossible to install the legacy Omnisharp extension.

**Comment by LiGoEX** [comment]
Have the same problem too!Legacy c# extension has been installed,and the Mono has been updated but the intellisense still won't show up!Any solution now?

**Comment by raldred** [comment]
Installed legacy c# and working fine.
Make sure you remove the latest c# extension first

**Comment by corum** [comment]
I can only confirm that, under Windows 8.1 pro x64 and Visual Studio 2015 PE, VSCode intellisense for Unity is totally broken.
![cattura di schermata 83](https://cloud.githubusercontent.com/assets/1676674/15466028/dbede282-20d7-11e6-9d39-f156b1221c03.png)
![cattura di schermata 84](https://cloud.githubusercontent.com/assets/1676674/15466034/e5204138-20d7-11e6-9806-3a806895ef6b.png)

**Comment by jlmakes** [comment]
@raldred Intellisense is working with Enums for you?

**Comment by raldred** [comment]
@jlmakes yes working fine
![enum working](https://www.dropbox.com/s/ptoqte2o946yr74/Screenshot%202016-06-08%2021.15.36.png?dl=1)
